### ISSUE TITLE
Npm module code not same as github master branch code

### ISSUE THREAD

**Issue by DennisAhaus** [anaptfox/cacheman-file#5]
Hi,
thank for the nice implementation. I think i have found an important issue:
Just installed `cacheman` with `cacheman-file` engine and started to checkout the code base.

# The error finding story

in cacheman package.json there is a block

       "devDependencies": {
           "cacheman-file": "latest",
          ...
        },

Then i started to test cacheman with mocha. 
Result were multiple errors and one of them was 

     1) cacheman should accept `file` as a valid engine:
        Error: ENOENT: no such file or directory, open 'c:\dev\projects\cacheman\tmp\cache:testing:test1.json'`

After all i started to checkout were the error comes from.... found line in 
   `cacheman-file/lib/index.js:156`
Then took a look at the git master branch code on the same file but on line 156 there was another code:

     var cacheFile = path.join(cwd, 'tmp', fileKey + '.json');

and also an completly new line at line number 155:
     var fileKey = key.replace(':', '_');   <<<< This seems to be the solvation of the original test error

# Summary

This seems to be a problem with current published module version/state of your module inside npm.
I checked out the package.json.version field but is still 0.0.8.

But if i compare the release tags there is a difference:
0.0.8     >>commit ff33d844d69c65e2b7bd4d59589ca0d35f8d6264
master  >>commit bdef7ad522e20fcf655964cb99bc3087f4cba569

maybe you should do a new npm build / publish with the current master version

**Comment by harlanj** [comment]
A new version has just been released. You can update your module to cachemanfile@0.1.0
